name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code ⬇️
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle 🐘
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper 🏃
        run: ./gradlew build
      - name: Get artifact name
        run: value=`ls ./build/libs`
      - name: Archive production artifacts ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: Store artifacts
          path: ./build/libs/$value
      - run: echo "🍏 This job's status is ${{ job.status }}."
