name: GitHub Actions
run-name: ${{ github.ref_name }} GitHub Actions 🚀
on: [push, pull_request]
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code ⬇️
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle 🐘
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper 🏃
        run: ./gradlew build -x test
      - name: Run tests 🧑‍⚕️
        run: ./gradlew test
      - name: Archive production artifacts ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./build/libs/saRestApi-*.jar
      - run: echo "🍏 This job's status is ${{ job.status }}."
  Push-to-artifactory:
    runs-on: ubuntu-latest
    needs: Build-Publish
    steps:
      - uses: jfrog/setup-jfrog-cli@v3
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_USER: ${{ secrets.JFROG_USERNAME }}
          JF_PASSWORD: ${{ secrets.JFROG_PASSWORD }}
      - run: |
          echo $env:JF_URL
          echo "$env:JF_USER"
          jf rt ping
