name: GitHub Actions
run-name: ${{ github.repository }} GitHub Actions 🚀
on: [push]
jobs:
  Build-Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code ⬇️
        uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle 🐘
        uses: gradle/gradle-build-action@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Run build with Gradle Wrapper 🏃
        run: ./gradlew build -x test --scan
      - name: Run tests 🧑‍⚕️
        run: ./gradlew test --scan
      - name: Archive production artifacts ⬆️
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: ./build/libs/saRestApi-*.jar
      - run: echo "🍏 This job's status is ${{ job.status }}."
